[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/@media/*"
  [headers.values]
    Accept-Ranges = "bytes"
    Cache-Control = "public, max-age=86400"
